const languages = ['html', 'css', 'javascript', 'react', 'node', 'postgres'];
console.log(`Languages array: ${languages}`);
const firstElement = languages[0];
console.log(`The 1st element is: ${firstElement}`);
const thirdElement = languages[2];
console.log(`The 3rd element is: ${thirdElement}`);
const length = languages.length;
console.log(`The length of the array is ${length}`);
const lastElement = languages[length - 1];
console.log(`The last element of the array is ${lastElement}`);
